debug: false
management.endpoints.web.exposure.include: "*"     #Spring boot Actuator

logging:
  level:
    com.examole.javajobjobproject: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace   # ???? ?????? ??  (??? ???? ?? ??)

#url: jdbc:h2:tcp://localhost/~/test
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/board
#    username: uno
#    password: thisisTESTpw!#%&
#    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:h2:mem:testdb
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true    #???? db ??
    hibernate.ddl-auto: create   #entity?? ??? ???? ??? ??(?? DDL)
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always     #resources? ?? sql? ?? ?????
  h2:
    console:
      enabled: true
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3.decoupled-logic: true





--- # --- ??? ????
#spring:
#  config.activate.on-profile: testdb    #tesd db ????? activation????? ? ??? ?? ??
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driverClassName: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none



